[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.54.0"
  HUGO_BASEURL = "/"

[context.production.environment]
  HUGO_VERSION = "0.54.0"
  RUBY_VERSION = "2.7.1"
